blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/support
    about: Please ask and answer questions here.
  - name: Security Policy
    url: https://github.com/MIACollaborative/justin-core/security
    about: Please review our security policy for reporting sensitive bugs.