import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    { type: 'doc', id: 'intro' },
    { type: 'doc', id: 'handlers' },
    { type: 'doc', id: 'concepts' },
    { type: 'doc', id: 'types' },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        { type: 'autogenerated', dirName: 'typeDoc' }
      ],
    },
  ],
};

export default sidebars;
